version: "3.7"
services:
  ubuntu-server:
    image: ubuntu:22.04  # 使用するUbuntuイメージを指定
    container_name: ubuntu-server
    command: tail -f /dev/null  # コンテナを終了させないためのコマンド
    networks:
      - invest_analyst_network
    volumes:
      - ~/investment_analyst:/work/investment_analyst  # ホストとコンテナ間でデータを共有する場合
    tty: true

  mysql-server:
    image: mysql:latest  # 使用するMySQLイメージを指定
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: root  # MySQLのルートパスワードを設定
    networks:
      - invest_analyst_network
    ports:
      - "3308:3308"  # ホストとコンテナのポートをマッピング
    volumes:
      - ./mysql_data:/var/lib/mysql  # データ永続化のためにMySQLデータをホストに保存
    restart: always

networks:
  invest_analyst_network:
